### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by helpdeskdan** [Skyedra/UnspamifyUbuntu#11]
Firstly, thanks for all this!  I was completely fine with the livepatch tip, but this has gotten totally out of hand.   Also, I don't think that "sudo pro config set apt_news=false" works.  

Now that I have to do all this junk, I find myself inclined to want said live patch tip gone as well.  This is easily accomplished by editing _/usr/lib/python3/dist-packages/UpdateManager/Dialogs.py_ and cobbling this function to return False.  

<pre>
    def _is_livepatch_supported(self):
        return False # Cut it out, #@&# it!
        di = distro_info.UbuntuDistroInfo()
        codename = get_dist()
        return di.is_lts(codename)

</pre>
Credit:  MikeR

**Comment by Skyedra** [comment]
I think our line numbers are differing a bit (I'm also on 24.04).  24 is a blank line, 278-315 spans the middle of several functions for me, and the file ends at 475.  Maybe my file is out of date

**Comment by helpdeskdan** [comment]
Should be:

 27 from gi.repository import GObject
 28 #import uaclient.api.u.pro.packages.updates.v1 as ua

287 #    def _get_ua_security_status(self):
288 #        self.ua_security_packages = []
289 #        self.ua_updates = []
290 #        t = threading.Thread(target=self._fetch_ua_updates, daemon=True)
(yada - till end of function)

486 #        self._get_ua_security_status()

**Comment by helpdeskdan** [comment]
I may have lied...

<pre>
Traceback (most recent call last):
  File "/usr/bin/software-properties-gtk", line 37, in <module>
    from softwareproperties.gtk.SoftwarePropertiesGtk import SoftwarePropertiesGtk
  File "/usr/lib/python3/dist-packages/softwareproperties/gtk/SoftwarePropertiesGtk.py", line 58, in <module>
    from .UbuntuProPage import UbuntuProPage
  File "/usr/lib/python3/dist-packages/softwareproperties/gtk/UbuntuProPage.py", line 27, in <module>
    from .DialogUaAttach import DialogUaAttach
  File "/usr/lib/python3/dist-packages/softwareproperties/gtk/DialogUaAttach.py", line 25, in <module>
    from uaclient.api.u.pro.attach.magic.initiate.v1 import initiate
</pre>

/usr/lib/python3/dist-packages/softwareproperties/gtk/SoftwarePropertiesGtk.py
comment out 
  58 #from .UbuntuProPage import UbuntuProPage
and at the end
1668 #    def init_ubuntu_pro(self):
1669 #        self.ubuntu_pro_page = UbuntuProPage(self)

Will THAT do it?  Hope so.  Stay tuned.

**Comment by helpdeskdan** [comment]
Last I checked, this is still valid as well:

/usr/lib/python3/dist-packages/softwareproperties/gtk/SoftwarePropertiesGtk.py
comment out
58 #from .UbuntuProPage import UbuntuProPage
and at the end
1668 # def init_ubuntu_pro(self):
1669 # self.ubuntu_pro_page = UbuntuProPage(self)
